/**
 * @file Plugin to force the `i` flag for comparison of attribute values. Originally generated by ChatGPT but manually reviewed, adjusted, and tested.
 */

import stylelint from 'stylelint';
import selectorParser from 'postcss-selector-parser';
import type { Root as PostcssRoot, Rule } from 'postcss';
import type { PostcssResult } from 'stylelint';
import type { Root as SelectorRoot, Attribute } from 'postcss-selector-parser';

const {
    createPlugin,
} = stylelint;

const ruleName = 'simbiat/require-attribute-i-flag';

/**
 * List of messages.
 */
const messages: Record<string, (attr: unknown) => string> = stylelint.utils.ruleMessages(ruleName, {
    /**
     * Return the error message.
     * @param attr - Attribute that triggered the rule.
     * @returns Formatted error message string.
     */
    expected: (attr: unknown) => {
        return `Expected attribute selector [${String(attr)}] to include the 'i' case-insensitive flag`;
    },
});

const meta = {
    fixable: true,
    url: 'https://github.com/simbiat/stylelint-plugin-simbiat',
};

/**
 * Process attributes in a selector and report those missing the `i` flag.
 * @param selectors - Parsed selector root from postcss-selector-parser.
 * @param raw_selector - Raw selector string for fix replacement.
 * @param result - PostCSS result object for reporting.
 * @param rule_node - PostCSS rule node being checked.
 */
function walkAttributes(
    selectors: SelectorRoot,
    raw_selector: string,
    result: PostcssResult,
    rule_node: Rule,
): void {
    selectors.walkAttributes((attr: Attribute) => {
        const attribute_name = attr.attribute;
        const attribute_value = attr.value?.replace(/^["']|["']$/gv, '') ?? '';
        const has_i_flag = attr.insensitive ?? false;

        if (has_i_flag || !attr.operator || !attribute_value || attribute_value === '' || attribute_value === 'undefined') {
            return;
        }

        const full_attribute = attr.toString();
        const raw_attribute = `${attribute_name}='${attribute_value}'`;
        const index = attr.sourceIndex;
        const end_index = index + full_attribute.length;
        const expected_message = messages['expected'];
        const error_message = typeof expected_message === 'function'
            ? expected_message(raw_attribute)
            : String(expected_message);

        stylelint.utils.report({
            result,
            ruleName,
            node: rule_node,
            message: error_message,
            index,
            endIndex: end_index,
            /**
             * Apply the fix.
             */
            fix() {
                rule_node.selector = raw_selector.replace(
                    full_attribute,
                    full_attribute.replace(/\]$/v, ' i]'),
                );
            },
        });
    });
}

/**
 * Stylelint rule implementation that walks all CSS rules checking attribute selectors.
 * @param primary - Primary option value (must be `true` to enable).
 * @returns PostCSS root walker function.
 */
function ruleFunction(primary: unknown): (root: PostcssRoot, result: PostcssResult) => void {
    return (root: PostcssRoot, result: PostcssResult): void => {
        const valid_options = stylelint.utils.validateOptions(result, ruleName, {
            actual: primary,
            possible: [true],
        });

        if (!valid_options) {
            return;
        }

        root.walkRules((ruleNode) => {
            const raw_selector = ruleNode.raws.selector?.raw ?? ruleNode.selector;
            // noinspection JSCheckFunctionSignatures false positive https://youtrack.jetbrains.com/issue/WEB-77817
            selectorParser((selectors) => {
                walkAttributes(selectors, raw_selector, result, ruleNode);
            })
                .processSync(raw_selector);
        });
    };
}

ruleFunction.ruleName = ruleName;
ruleFunction.messages = messages;
ruleFunction.meta = meta;

export default createPlugin(ruleName, ruleFunction as stylelint.Rule);
