// Originally generated by ChatGPT but manually reviewed, adjusted and tested.
// @ts-check
// Plugin to force the `i` flag for comparison of attribute values

import stylelint from 'stylelint';
import selectorParser from 'postcss-selector-parser';

const {
  createPlugin,
} = stylelint;

const ruleName = 'simbiat/require-attribute-i-flag';

/** @type {Record<string, ((...args: any[]) => string) | string>} */
const messages = stylelint.utils.ruleMessages(ruleName, {
  expected: /** @param {string} attr */(attr) => {
    return `Expected attribute selector [${attr}] to include the 'i' case-insensitive flag`;
  },
});

const meta = {
  fixable: true,
  url: 'https://github.com/simbiat/stylelint-plugin-simbiat',
};

function walkAttributes(selectors, raw_selector, result, rule_node) {
  selectors.walkAttributes((attr) => {
    const attribute_name = attr.attribute;
    const attribute_value = attr.value?.replace(/^["']|["']$/gv, '');
    const has_i_flag = attr.insensitive;

    if (has_i_flag || !attr.operator || !attribute_value || attribute_value === '' || attribute_value === 'undefined') {
      return;
    }

    const full_attribute = attr.toString();
    const raw_attribute = `${attribute_name}='${attribute_value}'`;
    //const index = raw_selector.indexOf(full_attribute);
    //const end_index = index + full_attribute.length;
    const index = attr.sourceIndex;
    const end_index = index + full_attribute.length;

    stylelint.utils.report({
      result,
      ruleName,
      node: rule_node,
      message: messages.expected(raw_attribute),
      index,
      endIndex: end_index,
      fix() {
        rule_node.selector = raw_selector.replace(
          full_attribute,
          full_attribute.replace(/\]$/v, ' i]'),
        );
      },
    });
  });
}

/** @type {import('stylelint').Rule} */
function ruleFunction(primary) {
  /** @param {import('postcss').Root} root @param {import('stylelint').PostcssResult} result */
  return (root, result) => {
    const valid_options = stylelint.utils.validateOptions(result, ruleName, {
      actual: primary,
      possible: [true],
    });

    if (!valid_options) {
      return;
    }

    root.walkRules((ruleNode) => {
      const raw_selector = ruleNode.raws.selector?.raw || ruleNode.selector;
      // noinspection JSCheckFunctionSignatures false positive https://youtrack.jetbrains.com/issue/WEB-77817
      selectorParser((selectors) => {
        walkAttributes(selectors, raw_selector, result, ruleNode);
      })
        .processSync(raw_selector);
    });
  };
}

ruleFunction.ruleName = ruleName;
ruleFunction.messages = messages;
ruleFunction.meta = meta;

export default createPlugin(ruleName, /** @type {import('stylelint').Rule} */ ruleFunction);
